"""rename to tour specific language

Revision ID: 0e359fa47759
Revises: f882b782b28b
Create Date: 2023-03-31 21:08:27.315944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e359fa47759'
down_revision = 'f882b782b28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_name', sa.String(length=50), nullable=True),
    sa.Column('site_url', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('refresh_interval', sa.Integer(), nullable=True),
    sa.Column('last_refresh', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_url')
    )
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tour_user_id'), ['user_id'], unique=True)

    op.create_table('tour_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_activity_id', sa.Integer(), nullable=True),
    sa.Column('activity_name', sa.String(length=100), nullable=True),
    sa.Column('activity_date', sa.Integer(), nullable=True),
    sa.Column('summary_polyline', sa.String(length=100), nullable=True),
    sa.Column('origin_site', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['origin_site'], ['tour.site_url'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tour_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tour_activities_user_id'), ['user_id'], unique=False)

    op.drop_table('user_activities')
    with op.batch_alter_table('origin_site', schema=None) as batch_op:
        batch_op.drop_index('ix_origin_site_user_id')

    op.drop_table('origin_site')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('origin_site',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('site_url', sa.VARCHAR(length=50), nullable=True),
    sa.Column('start_date', sa.INTEGER(), nullable=True),
    sa.Column('end_date', sa.INTEGER(), nullable=True),
    sa.Column('refresh_interval', sa.INTEGER(), nullable=True),
    sa.Column('last_refresh', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_url')
    )
    with op.batch_alter_table('origin_site', schema=None) as batch_op:
        batch_op.create_index('ix_origin_site_user_id', ['user_id'], unique=False)

    op.create_table('user_activities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strava_activity_id', sa.INTEGER(), nullable=True),
    sa.Column('activity_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('activity_date', sa.INTEGER(), nullable=True),
    sa.Column('summary_polyline', sa.VARCHAR(length=100), nullable=True),
    sa.Column('origin_site', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['origin_site'], ['origin_site.site_url'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tour_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tour_activities_user_id'))

    op.drop_table('tour_activities')
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tour_user_id'))

    op.drop_table('tour')
    # ### end Alembic commands ###
