"""reset for auth-server db changes

Revision ID: 6d905ee81451
Revises: 
Create Date: 2023-09-16 18:54:36.083583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d905ee81451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strava_webhook_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strava_webhook_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strava_webhook_subscription_subscription_id'), ['subscription_id'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('isadmin', sa.Boolean(create_constraint=1), nullable=True),
    sa.Column('strava_athlete_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_strava_athlete_id'), ['strava_athlete_id'], unique=True)

    op.create_table('strava_access_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['user.strava_athlete_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strava_access_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strava_access_token_access_token'), ['access_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_strava_access_token_athlete_id'), ['athlete_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_strava_access_token_expires_at'), ['expires_at'], unique=False)

    op.create_table('strava_refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['user.strava_athlete_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strava_refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strava_refresh_token_athlete_id'), ['athlete_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_strava_refresh_token_refresh_token'), ['refresh_token'], unique=False)

    op.create_table('tour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_uuid', sa.String(length=50), nullable=True),
    sa.Column('tour_name', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tour_uuid')
    )
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tour_user_id'), ['user_id'], unique=False)

    op.create_table('tour_activities',
    sa.Column('strava_activity_id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=100), nullable=True),
    sa.Column('activity_date', sa.Integer(), nullable=True),
    sa.Column('summary_polyline', sa.String(length=100), nullable=True),
    sa.Column('parent_tour', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['parent_tour'], ['tour.tour_uuid'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.public_id'], ),
    sa.PrimaryKeyConstraint('strava_activity_id', 'parent_tour')
    )
    with op.batch_alter_table('tour_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tour_activities_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tour_activities_user_id'))

    op.drop_table('tour_activities')
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tour_user_id'))

    op.drop_table('tour')
    with op.batch_alter_table('strava_refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strava_refresh_token_refresh_token'))
        batch_op.drop_index(batch_op.f('ix_strava_refresh_token_athlete_id'))

    op.drop_table('strava_refresh_token')
    with op.batch_alter_table('strava_access_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strava_access_token_expires_at'))
        batch_op.drop_index(batch_op.f('ix_strava_access_token_athlete_id'))
        batch_op.drop_index(batch_op.f('ix_strava_access_token_access_token'))

    op.drop_table('strava_access_token')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_strava_athlete_id'))

    op.drop_table('user')
    with op.batch_alter_table('strava_webhook_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strava_webhook_subscription_subscription_id'))

    op.drop_table('strava_webhook_subscription')
    # ### end Alembic commands ###
