"""remove site url from tour model

Revision ID: 790e683ebe5e
Revises: 052a8c994ce8
Create Date: 2023-04-06 19:54:29.677632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790e683ebe5e'
down_revision = '052a8c994ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('site_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_url', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
