"""remove unique constraint on tour user_id

Revision ID: 91d5b169da45
Revises: 12373337d7a4
Create Date: 2023-04-04 21:02:25.860263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d5b169da45'
down_revision = '12373337d7a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_index('ix_tour_user_id')
        batch_op.create_index(batch_op.f('ix_tour_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tour_user_id'))
        batch_op.create_index('ix_tour_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
