"""update Tour model to reflect webhook strategy

Revision ID: 9526127a3e91
Revises: e48e4b7c3bfd
Create Date: 2023-04-19 17:31:50.664492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9526127a3e91'
down_revision = 'e48e4b7c3bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_refresh', sa.Boolean(create_constraint=1), nullable=True))
        batch_op.drop_column('refresh_interval')
        batch_op.drop_column('last_refresh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_refresh', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('refresh_interval', sa.INTEGER(), nullable=True))
        batch_op.drop_column('auto_refresh')

    # ### end Alembic commands ###
