"""adds composite primary key to tour activities

Revision ID: aca5fa972b7d
Revises: 790e683ebe5e
Create Date: 2023-04-06 20:19:52.493498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca5fa972b7d'
down_revision = '790e683ebe5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_activities', schema=None) as batch_op:
        batch_op.alter_column('strava_activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('parent_tour',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('parent_tour',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('strava_activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
