"""remove auto refresh fields

Revision ID: cd5a3d8e0cba
Revises: 9526127a3e91
Create Date: 2023-05-09 11:01:08.186336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5a3d8e0cba'
down_revision = '9526127a3e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.drop_column('auto_refresh')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tour', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_refresh', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
