"""reset migration

Revision ID: f0723449d457
Revises: 
Create Date: 2023-03-30 20:55:55.567310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0723449d457'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('origin_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_origin_site_user'), ['user'], unique=True)
        batch_op.create_foreign_key(None, 'user', ['user'], ['uuid'])

    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_site', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'origin_site', ['origin_site'], ['site_url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('origin_site')

    with op.batch_alter_table('origin_site', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_origin_site_user'))
        batch_op.drop_column('user')

    # ### end Alembic commands ###
