"""reset migrations

Revision ID: f882b782b28b
Revises: 
Create Date: 2023-03-31 19:44:36.653943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f882b782b28b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('verified', sa.Boolean(create_constraint=1), nullable=True),
    sa.Column('strava_athlete_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_strava_athlete_id'), ['strava_athlete_id'], unique=True)

    op.create_table('origin_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=50), nullable=True),
    sa.Column('site_url', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('refresh_interval', sa.Integer(), nullable=True),
    sa.Column('last_refresh', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_url')
    )
    with op.batch_alter_table('origin_site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_origin_site_user_id'), ['user_id'], unique=True)

    op.create_table('strava_access_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['user.strava_athlete_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strava_access_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strava_access_token_access_token'), ['access_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_strava_access_token_athlete_id'), ['athlete_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_strava_access_token_expires_at'), ['expires_at'], unique=False)

    op.create_table('strava_refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['user.strava_athlete_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strava_refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strava_refresh_token_athlete_id'), ['athlete_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_strava_refresh_token_refresh_token'), ['refresh_token'], unique=False)

    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strava_activity_id', sa.Integer(), nullable=True),
    sa.Column('activity_name', sa.String(length=100), nullable=True),
    sa.Column('activity_date', sa.Integer(), nullable=True),
    sa.Column('summary_polyline', sa.String(length=100), nullable=True),
    sa.Column('origin_site', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['origin_site'], ['origin_site.site_url'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activities')
    with op.batch_alter_table('strava_refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strava_refresh_token_refresh_token'))
        batch_op.drop_index(batch_op.f('ix_strava_refresh_token_athlete_id'))

    op.drop_table('strava_refresh_token')
    with op.batch_alter_table('strava_access_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strava_access_token_expires_at'))
        batch_op.drop_index(batch_op.f('ix_strava_access_token_athlete_id'))
        batch_op.drop_index(batch_op.f('ix_strava_access_token_access_token'))

    op.drop_table('strava_access_token')
    with op.batch_alter_table('origin_site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_origin_site_user_id'))

    op.drop_table('origin_site')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_strava_athlete_id'))

    op.drop_table('user')
    # ### end Alembic commands ###
